# -*- coding: utf-8 -*-
"""sol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gberrRc65tFTYEfnyDoZt5lxtaHOIgo7
"""

import random
# import pandas as pd


def shuffle_deck(deck, seed=random.randint(1, 999999999999999999999999999999999)):
    deal = []
    random.Random(seed).shuffle(deck)
    deal = deck
    return {
        "deal": deal,
        "seed": seed
    }


suits = ['H', 'S', 'D', 'C']

ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K']

deck = [r+s for s in suits for r in ranks]

palos = ['O', 'C', 'E', 'B']

baraja48 = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'S', 'C', 'R']
baraja40 = ['A', '2', '3', '4', '5', '6', '7', 'S', 'C', 'R']

hf40 = [b+p for p in palos for b in baraja40]
hf48 = [b+p for p in palos for b in baraja48]

part1 = shuffle_deck(deck, 841097986032319523627500102373351)

print(part1['seed'])
print(part1['deal'])
